version: "3.9"
services:
  api-database:
    container_name: ts-rest-api-playground_database
    image: postgres:14.2
    restart: always
    ports:
      - "5432:5432"
    volumes: # persistent data storage between docker-host
      - api-database-vol:/var/lib/postgresql/data
      - ./database-scripts/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      # - POSTGRES_HOST_AUTH_METHOD=trust # ! MUST BE REMOVE FOR PROD

  api-server: # express server app
    container_name: ts-rest-api-playground_server
    image: ts-rest-api-playground_server-image
    restart: always
    ports:
      - "443:443"

    # production command
    command: node dist/app.js #--require dotenv/config
    # development command
    # command: nodemon src/app.ts --watch src/** #--r dotenv/config

    # env_file:
    #   - .env # ENV VARS for API Server App only
    environment:
      - API_SERVER_PORT=8080
      - API_SERVER_PORT_SECURE=443
      - DB_PORT=5432
      - DB_TYPE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_HOST=ts-rest-api-playground_database
      - DB_NAME=ts_rest_api_db

    volumes:
      - ./src:/app/src/
      - ./node_modules:/app/node_modules/

volumes:
  api-database-vol:
    name: "api-database-vol"
    driver: local
